bag/urls.py
"""Imports"""
from django.urls import path
from . import views

urlpatterns = [
    path('', views.view_bag, name='view_bag'),
    path('add/<item_id>/', views.add_to_bag, name='add_to_bag'),
    path('adjust/<item_id>/', views.adjust_bag, name='adjust_bag'),
    path('remove/<item_id>/', views.remove_from_bag, name='remove_from_bag'),
]

knits_and_pieces/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import handler404, handler500

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('home.urls')),
    path('products/', include('products.urls')),
    path('bag/', include('bag.urls')),
    path('checkout/', include('checkout.urls')),
    path('profile/', include('profiles.urls')),
    path('contact/', include('contact.urls')),
    path('custom/', include('custom.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'knits_and_pieces.views.handler404'
handler500 = 'knits_and_pieces.views.handler500'

products/urls.py
"""Imports"""
from django.urls import path
from . import views

urlpatterns = [
    path('', views.all_products, name='products'),
    path('<int:product_id>/', views.product_detail, name='product_detail'),
    path('add/', views.add_product, name='add_product'),
    path('edit/<int:product_id>', views.edit_product, name='edit_product'),
    path(
        'delete/<int:product_id>', views.delete_product, name='delete_product')
]

products/models.py
"""Imports"""
from django.db import models
from django.contrib.auth.models import User


class Category(models.Model):
    """A model for the product category"""
    class Meta:
        """Set spelling of category plural in admin panel"""
        verbose_name_plural = 'Categories'

    name = models.CharField(max_length=80)
    friendly_name = models.CharField(max_length=80, blank=True, default="")

    def __str__(self):
        return self.name

    def get_friendly_name(self):
        """Returns human readable name"""
        return self.friendly_name


class Tag(models.Model):
    """A model for a tag for a special addition to a product"""
    name = models.CharField(max_length=100)
    friendly_name = models.CharField(max_length=100, blank=True, default="")

    def __str__(self):
        return self.name

    def get_friendly_name(self):
        """Returns human readable name"""
        return self.friendly_name


class Product(models.Model):
    """A model for the product"""
    category = models.ForeignKey(
        'Category', null=True, blank=True, on_delete=models.SET_NULL)
    name = models.CharField(max_length=200, unique=True)

    ONE_SIZE = 'OS'
    SMALL = 'S'
    MEDIUM = 'M'
    LARGE = 'L'

    ITEM_SIZES = [
        (ONE_SIZE, 'One Size'),
        (SMALL, 'Small'),
        (MEDIUM, 'Medium'),
        (LARGE, 'Large'),
    ]
    item_sizes = models.CharField(
        max_length=20, blank=False, default=ONE_SIZE, choices=ITEM_SIZES)
    description = models.TextField()
    tag = models.ForeignKey(
        'Tag', null=True, blank=True, on_delete=models.SET_NULL, max_length=99)
    price = models.DecimalField(max_digits=6, decimal_places=2)

    ACRYLIC = 'AC'
    COTTON = 'CN'
    ACRYLIC_WOOL_MIX = 'AW'

    MATERIAL_TYPE = [
        (ACRYLIC, '100% Acrylic'),
        (COTTON, '100% Cotton'),
        (ACRYLIC_WOOL_MIX, '70% Acrylic, 30% Wool')
    ]

    material = models.CharField(
        max_length=2, blank=False, default=ACRYLIC, choices=MATERIAL_TYPE)
    machine_wash = models.BooleanField(default=True)
    image1 = models.ImageField(null=True, blank=True)

    RED = 'RED'
    ORANGE = 'OR'
    GREEN = 'GRN'
    BLUE = 'BLU'
    PINK = 'PI'
    YELLOW = 'YE'
    TEAL = 'TEA'
    GREY = 'GRY'
    PURPLE = 'PU'
    TURQUOISE = 'TU'
    BLACK = 'BLA'
    WHITE = 'WH'
    CREAM = 'CR'
    BEIGE = 'BEI'
    BROWN = 'BR'
    MAROON = 'MR'

    COLOUR_OPTIONS = [
        (RED, 'Red'),
        (ORANGE, 'Orange'),
        (GREEN, 'Green'),
        (BLUE, 'Blue'),
        (PINK, 'Pink'),
        (YELLOW, 'Yellow'),
        (TEAL, 'Teal'),
        (GREY, 'Grey'),
        (PURPLE, 'Purple'),
        (TURQUOISE, 'Turquoise'),
        (BLACK, 'Black'),
        (WHITE, 'White'),
        (CREAM, 'Cream'),
        (BEIGE, 'Beige'),
        (BROWN, 'Brown'),
        (MAROON, 'Maroon')
        ]

    colour1 = models.CharField(
        max_length=50, blank=False, choices=COLOUR_OPTIONS)
    colour2 = models.CharField(
        max_length=50, blank=True, default="", choices=COLOUR_OPTIONS)
    colour3 = models.CharField(
        max_length=50, blank=True, default="", choices=COLOUR_OPTIONS)
    colour4 = models.CharField(
        max_length=50, blank=True, default="", choices=COLOUR_OPTIONS)

    DREAMS = 'Dreams'
    SUN = 'Sun'
    FLOWER = 'Flower'
    ICE = 'Ice'
    STRIPE = 'Stripe'
    GRANNY = 'Granny'
    STRIPE_SPIKE = 'Spiked Stripe'
    LACY_SUN = 'Lacy Sun'
    MIX = 'Mix'

    PATTERN_OPTIONS = [
        (DREAMS, 'Dreams'),
        (SUN, 'Sun'),
        (FLOWER, 'Flower'),
        (ICE, 'Ice'),
        (STRIPE, 'Stripe'),
        (GRANNY, 'Granny'),
        (STRIPE_SPIKE, 'Spiked Stripe'),
        (LACY_SUN, 'Lacy Sun'),
        (MIX, 'Mix'),
    ]

    pattern_name = models.CharField(
        max_length=100, blank=True, default="", choices=PATTERN_OPTIONS)
    designer = models.CharField(max_length=50, blank=True, default="")
    can_custom_design = models.BooleanField(
        default=False, null=True, blank=True)

    def __str__(self):
        return self.name

products/forms.py
from django import forms
from .widgets import CustomClearableFileInput
from .models import Product, Category


class ProductForm(forms.ModelForm):
    """Form for product management to add products"""

    class Meta:
        model = Product
        fields = '__all__'

    image1 = forms.ImageField(
        label='Image1', required=False, widget=CustomClearableFileInput)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        categories = Category.objects.all()
        friendly_names = [(c.id, c.get_friendly_name()) for c in categories]

        try:
            alt_name = str(self.__getitem__('name')).split('"')[5]
        except Exception:
            alt_name = 'product image'

        self.fields['category'].choices = friendly_names

        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'border-black rounded-0'
            field.widget.attrs['alt'] = alt_name

products/views.py
"""Imports"""
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.db.models.functions import Lower
from .models import Product, Category, Tag
from .forms import ProductForm
# Create your views here.


def all_products(request):
    """ A view to show all products including search and sort queries.
    Variables defined as None to display when no sorting or filtering """

    products = Product.objects.all()
    query = None
    categories = None
    tags = None
    sort = None
    direction = None

    if request.GET:
        if 'sort' in request.GET:
            sortkey = request.GET['sort']
            sort = sortkey
            if sortkey == 'name':
                sortkey = 'lower_name'
                products = products.annotate(lower_name=Lower('name'))
            if sortkey == 'category':
                sortkey = 'category__name'
            if 'direction' in request.GET:
                direction = request.GET['direction']
                if direction == 'desc':
                    sortkey = f'-{sortkey}'
            products = products.order_by(sortkey)

        if 'category' in request.GET:
            categories = request.GET['category'].split(',')
            products = products.filter(category__name__in=categories)
            categories = Category.objects.filter(name__in=categories)

        if 'tag' in request.GET:
            tags = request.GET['tag'].split(',')
            products = products.filter(tag__name__in=tags)
            tags = Tag.objects.filter(name__in=tags)

        if 'q' in request.GET:
            query = request.GET['q']
            if not query:
                messages.error(request, "Please enter your search query!")
                return redirect(reverse('products'))

            queries = Q(
                name__icontains=query) | Q(description__icontains=query)
            products = products.filter(queries)

    current_sorting = f'{sort}_{direction}'

    context = {
        'products': products,
        'search_term': query,
        'current_categories': categories,
        'current_tags': tags,
        'current_sorting': current_sorting,
    }

    return render(request, 'products/products.html', context)


def product_detail(request, product_id):
    """ A view to show the product details """

    product = get_object_or_404(Product, pk=product_id)

    context = {
        'product': product,
    }
    return render(request, 'products/product_detail.html', context)


@login_required()
def add_product(request):
    """ Add a product to the store """
    if not request.user.is_superuser:
        messages.error(request, 'Sorry you are not authorised to do that')
        return redirect(reverse('home'))

    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES)
        if form.is_valid():
            product = form.save()
            messages.success(request, f'Successfully added {product.name}!')
            return redirect(reverse('product_detail', args=[product.id]))
        else:
            messages.error(
                request,
                'Failed to add product. Please ensure the form is valid.')
    else:
        form = ProductForm()

    template = 'products/add_product.html'
    context = {
        'form': form,
    }

    return render(request, template, context)


@login_required()
def edit_product(request, product_id):
    """ Edit a product in the store """
    if not request.user.is_superuser:
        messages.error(request, 'Sorry you are not authorised to do that')
        return redirect(reverse('home'))

    product = get_object_or_404(Product, pk=product_id)
    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES, instance=product)
        if form.is_valid():
            form.save()
            messages.success(
                request, f'{product.name} successfully updated!')
            return redirect(reverse('product_detail', args=[product.id]))
        else:
            messages.error(
                request, 'Update failed. Please ensure the form is valid.')
    else:
        form = ProductForm(instance=product)
        messages.info(request, f'You are editing {product.name}')

    template = 'products/edit_product.html'
    context = {
        'form': form,
        'product': product,
    }

    return render(request, template, context)


@login_required()
def delete_product(request, product_id):
    """ Delete a product from the store """
    if not request.user.is_superuser:
        messages.error(request, 'Sorry you are not authorised to do that')
        return redirect(reverse('home'))

    product = get_object_or_404(Product, pk=product_id)
    product.delete()
    messages.success(request, f'{product.name} deleted!')
    return redirect(reverse('products'))

products/templates/products/add_product.html
{% extends "base.html" %}
{% load static %}

{% block page_header %}
    <div class="container header-container">
        <div class="row">
            <div class="col"></div>
        </div>
    </div>
{% endblock %}

{% block content %}
    
    <div class="container">
        <div class="row text-center title-container">
            <div class="col">
                <hr>
                <h1 class="title-font display-colour">Add a Product</h1>
                <hr>
            </div>
        </div>

        <div class="row justify-content-center pt-2">
            <div class="col-10 col-lg-8 form-border-style pt-2">
                <form method="POST" action="{% url 'add_product' %}" class="form mb-2" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form | crispy }}
                    <div class="text-right">
                        <a class="btn btn-grey rounded-0" href="{% url 'products' %}">Cancel</a>
                        <button class="btn btn-red rounded-0" type="submit">Add Product</button>
                    </div>
                </form>
            </div>            
        </div>
    </div>
{% endblock %}

products/templates/products/edit_product.html
{% extends "base.html" %}
{% load static %}

{% block page_header %}
<div class="container header-container">
    <div class="row">
        <div class="col"></div>
    </div>
</div>
{% endblock %}

{% block content %}
<div class="container">
    <div class="row text-center title-container">
        <div class="col">
            <hr>
            <h1 class="title-font display-colour">Edit Product</h1>
            <hr>
        </div>
    </div>
    <div class="row justify-content-center pt-2">
        <div class="col-10 col-lg-8 form-border-style pt-2">
            <form method="POST" action="{% url 'edit_product' product.id %}" class="form mb-2"
                enctype="multipart/form-data">
                {% csrf_token %}
                {{ form | crispy }}
                <div class="text-right">
                    <a class="btn btn-grey rounded-0" href="{% url 'products' %}">Cancel</a>
                    <button class="btn update-btn rounded-0" type="submit">Update Product</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

products/templates/products/product_detail.html
{% extends "base.html" %}
{% load static %}

{% block page_header %}
<div>
    <div class="container header-container">
        <div class="row">
            <div class="col"></div>
        </div>
    </div>
</div>

{% endblock %}

{% block content  %}
<div class="container d-flex flex-column">
    <!-- product information -->
    <div class="row p-2">
        <!-- product image -->
        <div class="col-sm-6 card border shadow py-5 product-detail-image">
            <div class="image-container my-auto">
                {% if product.image1 %}
                <img class="product-detail-img card-img-top img-fluid" src="{{ product.image1.url }}"
                    alt="{{ product.name }}">
                {% else %}
                <img class="card-img-top img-fluid" src="{{ MEDIA_URL }}red_logo2.png" alt="red text Knits and Pieces">
                {% endif %}
            </div>
        </div>
        <!-- product details -->
        <div class="col-sm-6 py-1 card border shadow product-detail-text">
            <div class="row">
                <div class="card-body">
                    {% if product.tag %}
                    <p class="card-text text-right"><span class="product-tag">{{ product.tag.friendly_name }}!</span>
                    </p>
                    {% endif %}
                </div>
            </div>
            <div class="row">
                <h1 class="col card-title font-weight-bold text-left">{{ product.name }}</h1>
            </div>
            <div class="row">
                {% if request.user.is_superuser %}
                <small class="ml-3">
                    <a class="edit-btn text-white p-1" href="{% url 'edit_product' product.id %}">Edit</a>
                    <a class="delete-button text-white p-1"
                        href="{% url 'delete_product' product.id %}">Delete</a>
                </small>
                {% endif %}
            </div>
            <div class="row">
                <div class="col card-body">
                    {% if product.category %}
                    <p class="card-text info-text mt-2 mb-0">
                        <a href="{% url 'products' %}?category={{ product.category.name }}">
                            <i class="fas fa-tag mr-1"></i>{{ product.category.friendly_name }}
                        </a>
                    </p>
                    {% endif %}
                </div>
            </div>
            <div class="row">
                <div class="col card-body pb-0">
                    <h2 class="card-text lead font-weight-bold">€{{ product.price }}</h2>
                    <hr>
                    <p class="font-weight-bold">Description:</p> 
                    <p class="card-text">{{ product.description }}</p>
                    <hr>
                    <p class="font-weight-bold">Details:</p>
                    <p class="card-text"><strong> Main Colour(s)</strong>: {{ product.get_colour1_display }}
                        {% if product.colour2 %}, {{ product.get_colour2_display }}{% endif %}
                        {% if product.colour3 %}, {{ product.get_colour3_display }}{% endif %}
                        {% if product.colour4 %}, {{ product.get_colour4_display }}{% endif %}
                    </p>
                    <p class="card-text"><strong> Material:</strong> {{ product.get_material_display }}</p>
                    <p class="card-text"><strong>Size:</strong> {{ product.item_sizes }}</p>
                    <p class="card-text"><strong>Machine Wash:</strong>
                    {% if product.machine_wash %}Yes{% endif %}{% if not product.machine_wash %}No {% endif %}</p>

                    {% if product.designer %}
                    <p class="card-text"><strong>Designed by:</strong> {{ product.designer }}</p>
                    {% endif %}
                    {% if product.pattern_name %}
                    <p class="card-text"><strong>Pattern name:</strong> {{ product.pattern_name }}</p>
                    {% endif %}
                    {% if product.can_custom_design %}
                    <p class="card-text info-text"><strong>Contact us if you
                            would like to request a <a class="text-crimson" href="{% url 'custom' %}">custom order</a> of this item in your choice of colours or
                            sizes.</strong></p>
                    {% endif %}
                    <hr>
                </div>
            </div>

            <!-- form to add to basket -->
            <form class="form" action="{% url 'add_to_bag' product.id %}" method="POST">
                {% csrf_token %}
                <div class="form-row">
                    <div class="col-12">
                        <p><strong>Quantity:</strong></p>
                        <div class="form-group w-50">
                            <div class="input-group">
                                <div class="input-group input-group-{{ product.id }}">
                                    <div class="input-group-prepend">
                                        <button
                                            class="decrement-qty btn btn-grey btn-sm rounded-0 decrement-qty_{{ product.id }}"
                                            data-item_id="{{ product.id }}" aria-label="Subtract">
                                            <span class="icon">
                                                <i class="fas fa-minus"></i>
                                            </span>
                                        </button>
                                    </div>
                                    <input class="form-control qty_input id_qty_{{ product.id }}" type="number"
                                        name="quantity" value="1" min="1" max="99" data-item_id="{{ product.id }}" aria-label="quantity" >
                                    <div class="input-group-append">
                                        <button
                                            class="increment-qty btn btn-grey btn-sm rounded-0 increment-qty_{{ product.id }}"
                                            data-item_id="{{ product.id }}" aria-label="Add">
                                            <span class="icon">
                                                <i class="fas fa-plus"></i>
                                            </span>
                                        </button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="col-12">
                        <a href="{% url 'products' %}?category=throws,bedcovers,baby_blankets,cushion_covers,hats,gloves,face_masks" class="btn btn-grey rounded-0 mt-2">
                            <span class="icon">
                                <i class="fas fa-chevron-left"></i>
                            </span>
                            <span class="text-uppercase">Shop</span>
                        </a>
                        <input type="submit" class="btn btn-red rounded-0 text-uppercase mt-2" value="Add to Basket">
                    </div>
                    <input type="hidden" name="redirect_url" value="{{ request.path }}">
                </div>
            </form>
        </div>
    </div>



</div>

{% endblock %}
{% block postloadjs %}
{{ block.super }}
{% include 'products/includes/quantity_input_script.html' %}
{% endblock %}

products/templates/products/products.html
{% extends "base.html" %}
{% load static %}

{% block page_header %}

<div class="container header-container">
</div>

{% endblock %}

{% block content  %}
<div class="container-fluid">
    <div class="row text-center">
        <div class="col title-font display-colour d-sm-block bg-white pt-4">
            <h1>Shop</h1>
        </div>
    </div>
    <div class="row">
        <div class="col text-center mt3">
            {% for c in current_categories %}
            <a class="badge badge-pill" href="{% url 'products' %}?category={{ c.name }}">
                <span>{{c.friendly_name}}</span>
            </a>
            {% endfor %}
            <hr class="w-50 mb-1">
        </div>
    </div>
    <div class="row">
        <div class="col product-container col-10 offset-1">
            <div class="row mt-1 mb-2">
                <div class="col-12 col-md-6 my-auto order-md-last d-flex justify-content-center justify-content-md-end">
                    <div class="sort-select-wrapper w-50">
                        <select id="sort-selector"
                            class="custom-select custom-select-sm rounded-0 border border-{% if current_sorting != 'None_None' %}info{% else %}black{% endif %}" aria-label="sort-selector">
                            <option value="reset" {% if current_sorting == 'None_None' %}selected{% endif %}>Sort by...
                            </option>
                            <option value="price_asc" {% if current_sorting == 'price_asc' %}selected{% endif %}>Price
                                (low to high)</option>
                            <option value="price_desc" {% if current_sorting == 'price_desc' %}selected{% endif %}>Price
                                (high to low)</option>
                            <option value="name_asc" {% if current_sorting == 'name_asc' %}selected{% endif %}>Name
                                (A-Z)</option>
                            <option value="name_desc" {% if current_sorting == 'name_desc' %}selected{% endif %}>Name
                                (Z-A)</option>
                            <option value="category_asc" {% if current_sorting == 'category_asc' %}selected{% endif %}>
                                Category (A-Z)</option>
                            <option value="category_desc"
                                {% if current_sorting == 'category_desc' %}selected{% endif %}>Category (Z-A)</option>
                        </select>
                    </div>
                </div>
                <div class="col-12 col-md-6 order-md-first">
                    <p class="text-muted mt-3 text-center text-md-left">
                        {% if search_term or current_categories or current_sorting != 'None_None' %}
                        <span><a href="{% url 'products' %}">All Products</a> | </span>
                        {% endif %}
                        {{ products|length }} Products{% if search_term %} found for
                        "{{ search_term }}"{% endif %}
                    </p>
                </div>
            </div>
            <div class="row">
                {% for product in products %}
                <div class="product-card-container col-sm-6 col-md-6 col-lg-4 col-xl-3">
                    <div class="card h-100 border-1 shadow p-3">

                        {% if product.image1 %}
                        <a href="{% url 'product_detail' product.id %}">
                            <img class="card-img-top img-fluid all-products-img p-1" src="{{ product.image1.url }}"
                                alt="{{ product.name }}"></a>
                        {% else %}
                        <a href="{% url 'product_detail' product.id %}">
                            <img class="card-img-top img-fluid" src="{% static 'img/red_logo2.png' %}"
                                alt="{{ product.name }}"></a>
                        {% endif %}
                        <div class="card-body pb-1">
                            <h2 class="mb-0 font-weight-bold product-name">{{ product.name }}</h2>
                        </div>
                        <div class="card-footer bg-white pt-0 border-0 text-left">
                            <div class="row">
                                <div class="col">
                                    {% if product.tag %}
                                    <p class="mb-2 text-left"><span
                                            class="product-tag">{{ product.tag.friendly_name }}!</span></p>
                                    {% endif %}
                                    {% if product.category %}
                                    <p class="small mt-0 mb-0 info-text">
                                        <a href="{% url 'products' %}?category={{ product.category.name }}">
                                            <i class="fas fa-tag mr-1"></i>{{ product.category.friendly_name }}
                                        </a>
                                    </p>
                                    {% endif %}
                                    <h3 class="lead mb-0 text-left font-weight-bold">€{{ product.price }}</h3>
                                    {% if request.user.is_superuser %}
                                    <small>
                                        <a class="edit-btn p-1"
                                            href="{% url 'edit_product' product.id %}">Edit</a>
                                        <a class="delete-button bg-danger p-1"
                                            href="{% url 'delete_product' product.id %}">Delete</a>
                                    </small>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>
<div class="btt-button shadow-sm rounded-0 border" id="btt-button">
    <a class="btt-link d-flex h-100">
        <i class="fas fa-arrow-up mx-auto my-auto"></i>
    </a>
</div>

{% endblock %}

{% block postloadjs %}
{{ block.super }}

<script>
    let mybutton = document.getElementById("btt-button");
    window.onscroll = function () {
        scrollFunction();
    };

    function scrollFunction() {
        if (
            document.body.scrollTop > 20 ||
            document.documentElement.scrollTop > 20
        ) {
            mybutton.style.display = "block";
        } else {
            mybutton.style.display = "none";
        }
    }
    mybutton.addEventListener("click", backToTop);

    function backToTop() {
        document.body.scrollTop = 0;
        document.documentElement.scrollTop = 0;
    }
</script>

<!-- captures change event from sort selector, either resets sort value to default or gets new sort value and replaces GET values in url , jQuery code from Code Insitute Boutique Ado -->

<script>
    $('#sort-selector').change(function () {
        var selector = $(this);
        var currentUrl = new URL(window.location);
        var selectedVal = selector.val();
        if (selectedVal != "reset") {
            var sort = selectedVal.split("_")[0];
            var direction = selectedVal.split("_")[1];
            currentUrl.searchParams.set("sort", sort);
            currentUrl.searchParams.set("direction", direction);
            window.location.replace(currentUrl);
        } else {
            currentUrl.searchParams.delete("sort");
            currentUrl.searchParams.delete("direction");
            window.location.replace(currentUrl);
        }
    })
</script>
{% endblock %}